/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 clock.glb -T 
Files: clock.glb [3.38MB] > D:\workspace\DEMO\clock\public\model\clock-transformed.glb [186.77KB] (94%)
Author: hitheredearjohn (https://sketchfab.com/hitheredearjohn)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/clock-cd0e6a816e6942b587846dd1e866d59e
Title: Clock
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/clock-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.clock_main_0.geometry} material={materials.clock_metal} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.clock_main_1.geometry} material={materials.dial} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['12_0'].geometry} material={materials.Numbers} position={[-0.15, 0.408, -1.983]} rotation={[-Math.PI / 2, 0, 0]} scale={0.658} />
      <mesh geometry={nodes.middle_0.geometry} material={materials.hands_plastic} position={[0, 0.455, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.055} />
    </group>
  )
}

useGLTF.preload('/clock-transformed.glb')
